# Location: schedule_pro/pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  google_mobile_ads: ^4.0.0
  flutter_local_notifications: ^16.3.2
  timezone: ^0.9.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png